baseURL = "http://localhost:1313/"
languageCode = "en"
title = "long variables"
theme = "PaperMod"

[params]
  author = "long variables"
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowShareButtons = false
